<?php
//file : app/config/constants.php

return array(
	'SUPER_ADMINISTRATOR' => 1,
	'ADMINISTRATOR' => 2,
	'ADMIN' => 3,
	'BACKEND_PAGINATION_USER'=>10,
	'BACKEND_PAGINATION_PAGE'=>10,
	'BACKEND_PAGINATION_SLIDESHOW'=>10,
	'BACKEND_PAGINATION_AVERTISEMENT'=>10,
	'BACKEND_PAGINATION_STORE'=>10,
	'SLIDESHOW_RESIZE_WIDTH'=>100,
	'SLIDESHOW_RESIZE_HEGHT'=>100,
	'ADVERTISEMENT_RESIZE_WIDTH'=>100,
	'ADVERTISEMENT_RESIZE_HEGHT'=>100,
	'BACKEND_PAGINATION_MARKET'=>10,
	'MARKET_RESIZE_HEGHT'=>100,
	'MARKET_RESIZE_WIDTH'=>100,
	'STORE_RESIZE_WIDTH'=>100,
	'STORE_RESIZE_HEGHT'=>100,
	'USER_GROUP_PAGINATION'=>10,
	'HOMESHOP'=>'Homeshop',
	'PRIVATE_COMPANY'=>'Private company',
	'TRADITIONAL_MARKET'=>'Traditional Market',
	'SUPERMARKET'=>'Supermarket',
	'CLIENT_USER'=>4,
	'TABLE_NAME'=>array(
			'ACCOUNT_TYPE'=>'account_type',
			'ADV_PAGE'=>'adv_page',
			'ADV_CAT_PAGE'=>'category_adv_position',
			'ADV_CAT_PAGE_POSITION_MM'=>'cat_page_position_mm',
			'ADV_POSITION'=>'adv_position',
			'ADV_PAGE_POSITION_MM'=>'adv_page_position_mm',
			'ADVERTISEMENT'=>'advertisement',
			'LICENSE'=>'license',
			'ADVERTISER_PROFILE'=>'advertiser_profile',
			'CLIENT_TYPE'=>'client_type',
			'DISTRICT'=>'district',
			'IMAGE'=>'image',
			'LAYOUT'=>'layout',
			'M_CATEGORY'=>'m_category',
			'M_PAGE'=>'m_page',
			'MARKET'=>'market',
			'PRODUCT'=>'product',
			'PRODUCT_IN_STORE'=>'product_in_store',
			'PRODUCT_CONDITION'=>'product_condiction',
			'PROVINCE'=>'province',
			'S_CATEGORY'=>'s_category',
			'S_PAGE'=>'s_page',
			'SETTING'=>'setting',
			'SLIDESHOW'=>'slideshow',
			'STORE'=>'store',
			'TEMPLATE'=>'template',
			'USER'=>'user',
			'USER_TYPE'=>'user_type',
			'PERMISSION'=>'permission',
			'PRODUCT_TRANSFER_TYPE'=>'product_transfer_type'
		)
);